### ISSUE TITLE
How to start bots

### ISSUE THREAD

**Issue by josefredohd** [Fan7asy/OgarFeederBot#2]
Before making an issue please make sure that your issue is acctually an issue.

**Comment by Fan7asy** [comment]
Run these two commands in the folder.
`cd src`
`node index`

**Comment by Fan7asy** [comment]
I'm currently writing a Multi-User system, I will make sure to add instructions on how to run the bots.

**Comment by josefredohd** [comment]
where I hit the proxies

**Comment by Fan7asy** [comment]
No proxies needed :)

**Comment by josefredohd** [comment]
lol

**Comment by josefredohd** [comment]
I already started the bots but I do not see any

**Comment by Fan7asy** [comment]
Press 2

**Comment by Fan7asy** [comment]
and bang

**Comment by Fan7asy** [comment]
Remember this still isn't finished so it isn't fully operational

**Comment by josefredohd** [comment]
do they work!

**Comment by josefredohd** [comment]
Nice bots

**Comment by Fan7asy** [comment]
Thanks 🙂

**Comment by josefredohd** [comment]
work on gaver.io?

**Comment by Fan7asy** [comment]
No, not yet

**Comment by Fan7asy** [comment]
I first need to fix it and then I'll start expanding its capabilities.

**Comment by josefredohd** [comment]
Could you please add it?

**Comment by Fan7asy** [comment]
Check out #1 for any further info.

**Comment by Fan7asy** [comment]
and yes

**Comment by Fan7asy** [comment]
Later

**Comment by josefredohd** [comment]
Thank you very much, I will be waiting :)

**Comment by Fan7asy** [comment]
np 🙂

**Comment by josefredohd** [comment]
how to use spam chat

**Comment by josefredohd** [comment]
don't work in gota.io?
